services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: mcp_rag_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
